eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.88.132:8761/eureka/
      
server:
  port: 8763
  
spring:
  application:
    name: eshop-price-service
  datasource: 
    type: com.alibaba.druid.pool.DruidDataSource
    platform: mysql
    url: jdbc:mysql://120.79.46.90:3306/test
    username: root
    password: zcc910319